# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
logging:
  level:
    root: INFO
    org.qdrin.qfsm: DEBUG
spring:
  thymeleaf:
    cache: false
  main:
    show-banner: true
  security:
    basic:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        # open-in-view: false
  h2:
    console:
      enabled: true
      path: /console/
  datasource:
    # username: ${DB_USER:psi}
    # password: ${DB_PASSWORD:psi}
    # url: "jdbc:postgresql://localhost:5432/psi_db"
    # url: ${DB_URI}
    testOnBorrow: true
    validationQuery: select 1
  liquibase:
    enabled: false
  environment:
    istio-host: ${ISTIO_HOST:localhost}